### ISSUE TITLE
Sorry to say, but the evaluation code is messy!

### ISSUE THREAD

**Issue by JasonLeeFdu** [rimchang/RealBlur#4]
It is not well organized and i have to pay more time rewirte the evaluation code. Would you please fix it or even give us a little suggestion

**Comment by rimchang** [comment]
Use below command.

python evaluation_RealBlur_ecc --gt_root=your_dataset_path/RealBlur-J_ECC_IMCORR_centroid_itensity_ref --input_dir=your_output_path --core=1 

Output image's name should be in the same format as scene001_blur_1.png.

Could you explain your problem in more detail?

**Comment by rimchang** [comment]
Sorry, i found a typo in evaluation code.
I fixed it.
Please try again.

**Comment by JasonLeeFdu** [comment]
Thanks a lot, but an essential problem is that 
1. the trained model of SRN\DeblurGanv2 is not trained with only RealBlur-J, so have you consider provide one? I can't stop wondering the generalization of the benchmark.
2. I tried many times to run this file "evaluation_RealBlur_ecc", but it gives the results that don't match with those in the paper. Maybe I was calling the py file in a wrong way without the command you provide.

**Comment by rimchang** [comment]
1, We show performance of model trained only RealBlur-J in table 3. RealBlur dataset mainly contains uniform blurred images and low-light scenes. So, model trained only RealBlur may not generalize to diffrent dataset. 

2, Could you explain which results don't match?
